version: '3'
services:
  orders:
    image: openjdk:21
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8080:8080"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      MYSQL_DATABASE: banco-de-dados
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql